---
- name: Download binary
  become: false
  get_url:
    url: "https://github.com/noisebridge/rfid-access-control/releases/download/v{{ earl_version }}/earl-v{{ earl_version }}.{{ go_arch }}.tar.gz"
    dest: "/tmp/earl-{{ earl_version }}.{{ go_arch }}.tar.gz"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Unpack binary
  become: false
  unarchive:
    src: "/tmp/earl-{{ earl }}.{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/earl-{{ go_arch }}"
  delegate_to: localhost
  check_mode: false

- name: Deploy binary
  copy:
    src: "/tmp/earl-{{ go_arch }}"
    dest: "/usr/local/bin/earl"
    mode: 0755
    owner: root
    group: root
  notify: restart earl
  when: not ansible_check_mode
